[package]
name = "crafty_novels"
authors = ["RemasteredArch"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/RemasteredArch/ip_geo/"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["cli"]
# members = ["cli", "gui"]

[dependencies]
thiserror = "1.0.63"
